[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cil]>=1.9.4",
    "openai>=1.86.0",
    "requests>=2.32.4",
]
